name = "ok-tumor"
bin = "bin/ok-tumor"
vcs = "git"
with_pop = true
with_sqlite = true
with_dep = false
with_webpack = true
with_nodejs = true
with_yarn = true
with_docker = false
with_grifts = true
as_web = true
as_api = false
